---
title: "HW 5"
author: "Keegan Burr"
date: "11/06/2024"
output:
  pdf_document: default
  html_document:
    number_sections: yes
fontsize: 12pt
---

This homework is meant to give you practice in creating and defending a position with both statistical and philosophical evidence.  We have now extensively talked about the COMPAS ^[https://www.propublica.org/datastore/dataset/compas-recidivism-risk-score-data-and-analysis] data set, the flaws in applying it but also its potential upside if its shortcomings can be overlooked.  We have also spent time in class verbally assessing positions both for an against applying this data set in real life.  In no more than two pages ^[knit to a pdf to ensure page count] take the persona of a statistical consultant advising a judge as to whether they should include the results of the COMPAS algorithm in their decision making process for granting parole.  First clearly articulate your position (whether the algorithm should be used or not) and then defend said position using both statistical and philosophical evidence.  Your paper will be grade both on the merits of its persuasive appeal but also the applicability of the statistical and philosohpical evidence cited.  
\newline
\newline
  COMPAS was an algorithm used to support judges' discretion in parole hearings from Florida to Wisconsin. It had an accuracy of 64%, but despite its accuracy, the algorithm was scrutinized by many different people across the nation. After looking into the algorithm, it was shown to exhibit bias against certain groups of people, particularly black individuals. These individuals were determined to be far more likely to be incorrectly judged as a higher risk of recidivism, while white defendants were found far more likely than black defendants to be incorrectly flagged as low risk. As one can imagine, this sparked controversy across the nation, so as a statistical consultant advising a judge on using the COMPAS algorithm in decision-making, I would strongly advise against relying on the algorithm. Although statistically, it is usable to an extent, the moral and ethical implications and the limitations in accuracy and fairness make it hard to recommend its use. Especially for something that is extremely impactful and affects the lives of so many.
\newline
\newline
  As previously mentioned the COMPAS algorithm is 64% accurate in predicting recidivism. While this figure would suggest a reasonable predictive power, it is important to note the algorithm has been heavily criticized for violating key fairness criteria. In terms of fairness criteria, sufficiency is upheld, but for independence, COMPAS fails to meet statistical parity because there is clear evidence of disparate impact. Even though race is not directly used as a variable in the COMPAS algorithm, other proxies like zip code that are used, create racial biases indirectly. On top of that, the algorithm does not satisfy equalized odds. This means the error rates differ significantly between different groups. Specifically in the case of COMPAS, the false positive rates for black defendants are much higher than for white defendants, which means black individuals are more often incorrectly classified. This inconsistency in error rates further showcases the lack of fairness in the algorithm. So, from a statistical standpoint, while the algorithm may be reasonably accurate in assisting judges, its limitations in fairness should raise many concerns about its reliability.
\newline
\newline
	In terms of philosophical frameworks, the COMPAS algorithm also presents ethical concerns that should make people reconsider its usage. From a deontological perspective, the use of COMPAS can be seen as morally impermissible because it fails to uphold Kant’s second formulation of the categorical imperative. In this formulation, it states that individuals should be treated as ends themselves and never merely as means to an end. By relying on an algorithm that produces biased outcomes, the justice system reduces these defendants to data points. Then Utilitarianism offers a different yet equally critical perspective on the use of COMPAS. Although a utilitarian might initially consider the algorithm as beneficial, since it leads to reduced recidivism rates and “increases public safety,” it significantly harms specific groups which would likely outweigh these perceived advantages. It has been proven the algorithm has been shown to produce worse sentences for minority defendants and these outcomes lead to severe psychological, social, and economic consequences. Overall, a utilitarian would find this unacceptable because the general consequences created by the algorithm would outweigh the social benefits.
\newline
\newline
	The concept of "fairness as equality" would also raise concerns that would challenge COMPAS. In this principle, all individuals are said to deserve equal treatment, yet the algorithm has shown bias against certain groups of people, clearly violating this principle. By discriminating against specific groups, the use of COMPAS not only fails to uphold principles of equality but also risks creating a lack of trust in the judicial process, making it a deeply flawed tool in terms of fairness.
\newline
\newline
	Overall, while the COMPAS algorithm aims to support judges in making more data-driven decisions, its significant ethical and statistical shortcomings cannot be overlooked. Despite its 64% accuracy, the algorithm's biases against minority groups undermine the fairness and reliability of its predictions. Additionally, the inability to meet essential fairness criteria, such as independence and equalized odds really shows the risk of discrimination against particular groups. Then based on moral frameworks, in deontology COMPAS violates the moral imperative to treat individuals as ends rather than mere means, and in utilitarianism, the significant consequences for minority groups far outweigh the perceived benefits. Finally, the principle of "fairness as equality" further emphasizes the algorithm’s failure to provide equal treatment. So, based on all of these concerns, I believe COMPAS is an algorithm that is extremely flawed and I would strongly advise against relying on this algorithm to a judge.